### PR TITLE
add nrTBS

### PR DESCRIPTION
**Pull request by zulfadlizainal**
get tb size function supported for both one and two codewords.

### CODE REVIEW

**Comment by catkira** [comment]
nice work. 
I have just one request, can you use the numpy math functions instead of the math package? It would make the code more consistent with the rest of py3gpp. Thanks!

**Comment by catkira** [comment]
I did some cosmetic improvements

**Comment by catkira** [comment]
can you also add a test in tests/matlab and also a simple hard coded test that does not depend on matlab and can run on CI?

**Comment by zulfadlizainal** [comment]
> can you also add a test in tests/matlab and also a simple hard coded test that does not depend on matlab and can run on CI?
> 
> tests/test_nrTBS.py and tests/matlab/test_nrTBS.py

ok let me figure out on how to do that. probably not so soon though :)

**Comment by catkira** [comment]
then just add the hardcoded test and we can add the matlab test later in another PR.

**Pull request merged**
