### PR TITLE
nrPDSCHDMRS function

### PR DESCRIPTION
**Pull request by vborchsh**
There is no proper checks of combination of input parameters at the moment. And, there is no support for ```DMRSLength=2``` parameter, at the moment.

I'm planning to add these things after full synchronization of my code with this repository.

### CODE REVIEW

**Comment by catkira** [comment]
can You also add tests that work without Matlab?
Something that uses fixed data would be enough.

**Comment by vborchsh** [comment]
> can You also add tests that work without Matlab?
> Something that uses fixed data would be enough.

This is very tight question. For sure, I can do it.

But if we need a proper test we need a lot of data: binary or csv or something else - you can imagine the number of combinations of parameters even for simple channels. This means dramatically increasing size of repository. And this files will be hardcoded - nobody has an idea about source and data in the files.
 
In the other hand I can cover couple of cases this way, but this is not enough, obviously.

What do you think about test environment, in general?

**Comment by catkira** [comment]
I think we can be practical for now and cover only a few hardcoded cases in the tests that don't use matlab for now. At least build breaks will become visible quickly that way.
As the functionality of py3gpp increases we can do more combined tx-rx / mod-demod tests that cover more cases without using fixed data.

**Comment by vborchsh** [comment]
Ok, agree

**Comment by vborchsh** [comment]
Done with it. Here are two hardcoded tests for PDSCHDMRS & PDSCHDMRSIndices

**Pull request merged**
