### PR TITLE
mod nrPathLossConfig

### PR DESCRIPTION
**Pull request by zulfadlizainal**
Convert def to class to make function property call similar as matlab docs.

### CODE REVIEW

**Comment by catkira** [comment]
can you solve the conflicts?

**Comment by zulfadlizainal** [comment]
thank you for your feedback. ill try to find out how to that.
once successful ill request new pull request and close this.

**Comment by zulfadlizainal** [comment]
I have rebase the current brach and looks like conflicts resolve. Thank you.

**Comment by catkira** [comment]
Why do you have this at the end?

```python
# Create an instance of NrPathLossConfig
pathlossconf = nrPathLossConfig()
```

**Comment by zulfadlizainal** [comment]
> Why do you have this at the end?
> 
> ```python
> # Create an instance of NrPathLossConfig
> pathlossconf = nrPathLossConfig()
> ```

To allow similar function call as below documentation link
It can be deleted, but user will have to define manually in case they follow this documentation
https://ch.mathworks.com/help/5g/ref/nrpathlossconfig.html#d124e80501

**Comment by catkira** [comment]
I think it should be deleted. In Matlab the user also has to create the object himself.

**Comment by zulfadlizainal** [comment]
> I think it should be deleted. In Matlab the user also has to create the object himself.

I see. got it, will move this line to example below. thanks.

**Pull request closed without merging**
