### PR TITLE
Add phase compensation to nrOFDMModulate() and nrOFDMDemodulate()

### PR DESCRIPTION
**Pull request by catkira**

### CODE REVIEW

**Comment by catkira** [comment]
@vborchsh can u review this?

**Comment by vborchsh** [comment]
Fine for me. But I can't check if the new test is connected to pytest flow?

**Comment by catkira** [comment]
I think pytest runs all files that have tests in them in the tests-directory. It would be cool If You could create matlab tests for nrOFDMModulate() and nrOFDMDemodulate() sometime - I don't have Matlab running in Linux (yet).

**Comment by vborchsh** [comment]
Ahhhh, ok, I see. Ok, I'll do it in a couple of days. So, you can merge it as is, or I can extend this branch with tests. It's up to you.

**Comment by catkira** [comment]
I will merge it now because I need it for some experiments. You can create a new PR for the Matlab tests. I bet You will find some things that are wrong, I will help fixing it then.

**Pull request merged**
