### PR TITLE
nrPDSCHPTRS

### PR DESCRIPTION
**Pull request by vborchsh**
Finished it

### CODE REVIEW

**Comment by catkira** [comment]
hmm strange, the lint CI is also running in this PR, but it shouldn't right, because you disabled it?

**Comment by vborchsh** [comment]
I added rule to pass through even failed pipelines in `lint` stage (quite ugly hack, must be changed, I guess). But now it failed in the very beginning:
image

**Comment by catkira** [comment]
Can you add this for the deployment step?
`if: github.event_name != 'pull_request'`
I got it from [here](https://stackoverflow.com/questions/66205887/only-run-github-actions-step-if-not-a-pull-request)

**Comment by catkira** [comment]
These 3 steps should not get executed in a PR
```yaml
      - name: upload pylint badge
        uses: actions/configure-pages@v1
        continue-on-error: true

      - name: Deploy to GitHub Pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: 'badge'
        continue-on-error: true
      - id: deployment
        uses: actions/deploy-pages@master
        continue-on-error: true
```

**Comment by catkira** [comment]
ok I will try to fix it in a separate PR

**Pull request merged**
